{{- if .Values.roleBinding.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "tunnel-operator.roleBindingName" . }}
  namespace: {{ include "tunnel-operator.namespaceName" . }}
  labels:
    {{- include "tunnel-operator.labels" . | nindent 4 }}
  {{- with .Values.roleBinding.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
subjects:
  - kind: ServiceAccount
    name: {{ include "tunnel-operator.serviceAccountName" . }}
    namespace: {{ include "tunnel-operator.namespaceName" . }}
roleRef:
  kind: Role
  name: {{ include "tunnel-operator.roleName" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
